---
# tasks file for ethereum-validator
- name: Update system
  import_tasks: 00_update_system.yml

- name: Setup firewall
  import_tasks: 01_setup_firewall.yml

- name: Setup NTP
  import_tasks: 02_setup_ntp.yml

- name: Setup Geth
  import_tasks: 03_setup_geth.yml

- name: Setup Prysm
  import_tasks: 04_setup_prysm.yml

- name: Setup Monitoring
  block:
    - name: Setup Prometheus
      import_tasks: 05_setup_prometheus.yml

#     - name: Setup Node Exporter
#       import_tasks: 06_setup_node_exporter.yml

#     - name: Setup JSON Exporter
#       import_tasks: 06_setup_json_exporter.yml

#     - name: Setup Blackbox Exporter
#       import_tasks: 06_setup_blackbox_exporter.yml

#     - name: Setup Grafana
#       import_tasks: 07_setup_grafana.yml
  when: ethv_monitoring
